# Generated by Django 3.1.2 on 2021-02-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pib',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
