# Generated by Django 3.1.2 on 2021-02-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_profile_pib'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pib',
            new_name='profile_pic',
        ),
    ]
